name: flashlight-xdebug-prestashop
services:
  prestashop:
    image: prestashop/prestashop-flashlight:1.7.8.11-7.4
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PS_DOMAIN=localhost:8000
      - INIT_SCRIPTS_DIR=/tmp/init-scripts
      - INIT_SCRIPTS_USER=root
      - POST_SCRIPTS_DIR=/tmp/post-scripts
      - XDEBUG_ENABLED=true
    volumes:
      - ./PrestaShop:/var/www/html:rw
      - type: bind
        source: ./modules/klaviyopsautomation
        target: /var/www/html/modules/klaviyopsautomation
      - ./post-scripts:/tmp/post-scripts
    ports:
      - 8000:80

  mysql:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 3309:3306
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
